### ISSUE TITLE
java.lang.NoClassDefFoundError: com.avos.avoscloud.AVPushWebSocketClient

### ISSUE THREAD

**Issue by codetalks-new** [leancloud/android-sdk-all#110]
经常,但是不是总是出现这个问题.
```java
11-16 11:22:46.626 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.xypuke.texaspoker, PID: 23852
                                     java.lang.NoClassDefFoundError: com.avos.avoscloud.AVPushWebSocketClient
                                         at com.avos.avoscloud.AVPushConnectionManager.createNewWebSocket(AVPushConnectionManager.java:190)
                                         at com.avos.avoscloud.AVPushConnectionManager.access$000(AVPushConnectionManager.java:30)
                                         at com.avos.avoscloud.AVPushConnectionManager$1.onServerAddress(AVPushConnectionManager.java:49)
                                         at com.avos.avospush.push.AVPushRouter.fetchPushServer(AVPushRouter.java:140)
                                         at com.avos.avoscloud.AVPushConnectionManager.initConnection(AVPushConnectionManager.java:112)
                                         at com.avos.avoscloud.AVPushConnectionManager.initConnection(AVPushConnectionManager.java:101)
                                         at com.avos.avoscloud.AVPushConnectionManager.<init>(AVPushConnectionManager.java:73)
                                         at com.avos.avoscloud.AVPushConnectionManager.getInstance(AVPushConnectionManager.java:94)
                                         at com.avos.avoscloud.PushService.onCreate(PushService.java:100)
                                         at android.app.ActivityThread.handleCreateService(ActivityThread.java:2910)
                                         at android.app.ActivityThread.access$2000(ActivityThread.java:153)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:5524)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by jwfing** [comment]
请确保你在 build.gradle 中加入了如下依赖
`compile ('cn.leancloud.android:avoscloud-push:v4.5.4@aar'){transitive = true}`

**Comment by codetalks-new** [comment]
@jwfing  Hi 谢谢回复.
 对于 依赖我是加了. 但是没有加 `{ transitive = true }` 的配置.
加了之后会导致 android-support: 18.+ 这个无法解析.
由于我项目已经有对 support 库的依赖. 然后我就到push 项目中的 build.gradle 看他依赖了哪些库.
然后直接添加进来作为依赖了.
即添加了下面两行:

```groovy
    implementation 'cn.leancloud.android:Java-WebSocket:1.3.2-leancloud'
    implementation 'com.google.protobuf:protobuf-java:3.4.0'
```

另外个人建议, 文档上还是加一下这个说明,即说明需要依赖 上面两个库. 我比较希望清楚的知道有什么依赖. 以减少依赖出错的问题.
