### ISSUE TITLE
收到的 AVIMAudioMessage fileUrl 为空

### ISSUE THREAD

**Issue by codetalks-new** [leancloud/android-sdk-all#146]
已经是使用最新版本的 SDK (4.6.1)
然后测试 getAVFile 结果发生如下异常
```java
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
                                      at com.avos.avoscloud.im.v2.messages.AVIMFileMessage.getAVFile(AVIMFileMessage.java:78)
                                      at .controller.GameActivity.handleAudioMessage(GameActivity.kt:2125)
                                      at controller.GameActivity.access$handleAudioMessage(GameActivity.kt:125)
                                      at controller.GameActivity$GameAudioMessageHandler.onMessage(GameActivity.kt:2115)
                                      at com.avos.avoscloud.im.v2.MessageHandler.processMessage(MessageHandler.java:33)
                                      at com.avos.avoscloud.im.v2.MessageHandler.processEvent0(MessageHandler.java:26)
                                      at com.avos.avoscloud.AVIMEventHandler$1.run(AVIMEventHandler.java:13)
                                      at android.os.Handler.handleCallback(Handler.java:754)
                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                      at android.os.Looper.loop(Looper.java:163)
```

**Comment by jwfing** [comment]
你这个消息是怎么发送的？是否有出错？

**Comment by codetalks-new** [comment]
@jwfing 

发送代码如下:
```kotlin
       log.i("send voice $audioPath")
        val audiotMsg = AVIMAudioMessage(audioPath)
        con.sendMessage(audiotMsg,object:AVIMConversationCallback(){
            override fun done(error: AVIMException?) {
                if (error == null){
                    log.i("send success")
                    this@GameActivity.showSuccess("已发送")
                    GameSound.msgSended.play(this@GameActivity)
                }else{
                    log.e(error.localizedMessage)
                    this@GameActivity.showError("语音发送失败")
                }
            }
        })
```
查看日志文件路径没有问题:  

> [main][1]:2104 - send voice /storage/emulated/0/Android/data/com.xypuke.texaspoker/cache/record_1514906380149.aac

上面的 sendMessage 也提示发送成功. leancloud 后台也有对应文件.

![image](https://user-images.githubusercontent.com/726774/34488632-3a283b10-f014-11e7-8a91-2c7eaf3a30ce.png)

**Comment by codetalks-new** [comment]
@jwfing hi 知道 fileUrl 为什么为 null 吗?
即使不抛出异常了,但是这个 fileUrl 为 null 我收到这条语音消息也是为空啊.

**Comment by simiwe** [comment]
这个 issues close 了，但是问题好像还没解决呢 @jwfing 。
