### ISSUE TITLE
报 Exception

### ISSUE THREAD

**Issue by jwfing** [leancloud/android-sdk-all#20]
java.lang.RuntimeException:
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2905)
at android.app.ActivityThread.access$1900(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method:0)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.IllegalStateException:
at com.avos.avoscloud.AVInstallation.readInstallationFile(Unknown Source:0)
at com.avos.avoscloud.AVInstallation.getCurrentInstallation(Unknown Source:0)
at com.avos.avoscloud.PushService.getConnectionManagerInstance(Unknown Source:0)
at com.avos.avoscloud.PushService.onCreate(Unknown Source:0)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2895)

java.lang.RuntimeException:
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3307)
at android.app.ActivityThread.-wrap5(ActivityThread.java:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6310)
at java.lang.reflect.Method.invoke(Native Method:0)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Caused by: java.lang.IllegalStateException:
at com.avos.avoscloud.AVInstallation.readInstallationFile(Unknown Source:0)
at com.avos.avoscloud.AVInstallation.getCurrentInstallation(Unknown Source:0)
at com.avos.avoscloud.PushService.getConnectionManagerInstance(Unknown Source:0)
at com.avos.avoscloud.PushService.onCreate(Unknown Source:0)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3297)

**Comment by jwfing** [comment]
这个 exception 应该是我们 sdk 里面主动抛出来的，因为开发者在调用 pushservice 之前没有主动调用 avoscloud.initialize 函数。
