### ISSUE TITLE
Target sdk 28出现崩溃

### ISSUE THREAD

**Issue by libxzr** [leancloud/android-sdk-all#203]
08-14 21:52:56.688 7045-7139/xzr.La.systemtoolbox E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: xzr.La.systemtoolbox, PID: 7045
    java.lang.NoClassDefFoundError: Failed resolution of: [Lorg/apache/http/Header;
        at com.avos.avoscloud.AsyncHttpResponseHandler.getHeaders(AsyncHttpResponseHandler.java:52)
        at com.avos.avoscloud.AsyncHttpResponseHandler.onResponse(AsyncHttpResponseHandler.java:42)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.Header" on path: DexPathList[[zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/base.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_dependencies_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_resources_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_0_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_1_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_2_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_3_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_4_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_5_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_6_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_7_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_8_apk.apk", zip file "/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/lib/arm64, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/base.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.avos.avoscloud.AsyncHttpResponseHandler.getHeaders(AsyncHttpResponseHandler.java:52) 
        at com.avos.avoscloud.AsyncHttpResponseHandler.onResponse(AsyncHttpResponseHandler.java:42) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/xzr.La.systemtoolbox-FCSc2LCLVUP6itUHOeBSkQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
08-14 21:52:56.695 7045-7139/xzr.La.systemtoolbox E/AndroidRuntime:     at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by libxzr** [comment]
手动增加依赖 org.apache.httpcomponents:httpcore:4.4.2 后即可解决
